### ISSUE TITLE
An option to change default browser

### ISSUE THREAD

**Issue by Nil-Zil** [Jasonlhy/VSCode-Browser-Sync#1]
Hi, it's a great extension. I wonder if this can provide an option for changing default browser to open the html? I know that Browsersync has an `browser` option.

**Comment by Jasonlhy** [comment]
Currently no, but I believe it can be changed according to [the documentation here](https://www.browsersync.io/docs/options#option-browser). But where would you like to put this setting? The modal input dialog or project configuration file?

**Comment by Nil-Zil** [comment]
I think project configuration file or vscode default settings would be good.

**Comment by Jasonlhy** [comment]
@Nil-Zil Added a configuration paremter You can set it under workspace setting or user setting. Give it a try 👍

**Comment by Nil-Zil** [comment]
Thank you for your timely response! I found that no browser was opened after I start the server. I think I used it correctly because I can open it at side panel, but it does not open in browser automatically now.

**Comment by Jasonlhy** [comment]
@Nil-Zil Omg I forgot if ([]) evaulate to true. I should always review [this article] (http://jasonlhy.me/javascript-boolean-experience/). I will fix it as soon as possible

**Comment by Jasonlhy** [comment]
@Nil-Zil This problem should be fixed in new version 1.1.1. I just published it.

**Comment by Nil-Zil** [comment]
Thank you very much! It works! For default "chrome" option I still cannot open my chrome, but I reviewed [this](https://github.com/BrowserSync/grunt-browser-sync/issues/56) and changed it to "google chrome" or "Google Chrome" on macOS 10.12.6. Then it works!

**Comment by Jasonlhy** [comment]
I need to use "google chrome" on window :octocat: , I will update the readme and package json later. Thanks.
